### ISSUE TITLE
The call crashes when there is no data available

### ISSUE THREAD

**Issue by plitkey** [pnuu/fmiopendata#3]
print(arglist)
['fmisid=101004', 'starttime=2019-12-10T09:20:00Z', 'endtime=2019-12-10T09:50:00Z']
>>> obs = download_stored_query("fmi::observations::weather::multipointcoverage",args=arglist)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pli/mypython38venv/lib/python3.8/site-packages/fmiopendata/wfs.py", line 123, in download_stored_query
    return download_and_parse(query_id, args=args)
  File "/home/pli/mypython38venv/lib/python3.8/site-packages/fmiopendata/multipoint.py", line 107, in download_and_parse
    return MultiPoint(xml, query_id)
  File "/home/pli/mypython38venv/lib/python3.8/site-packages/fmiopendata/multipoint.py", line 45, in __init__
    self._parse(self._xml)
  File "/home/pli/mypython38venv/lib/python3.8/site-packages/fmiopendata/multipoint.py", line 65, in _parse
    positions = np.fromstring(xml.findtext(wfs.GMLCOV_POSITIONS), dtype=float, sep=" ")
TypeError: a bytes-like object is required, not 'NoneType'

When I load the data using fmi web page, everything is missing, only '-' for the observations. I would prefer here NaN or '-' over crash.

I tried to load Kaisaniemi weather for the same time period, it looks ok in the fmi web page load, but crashes with my python query, so maybe it is something else than no data problem.

This seems to have been temporary problem, the queries work now.

**Comment by pnuu** [comment]
Thanks for the report, and sorry for the delayed response. This is now fixed in the current `master` branch and version 0.2.4 available from PyPi.
