### ISSUE TITLE
Download and calibrate latest radar reflectivity (dBZ) composite fails

### ISSUE THREAD

**Issue by JaniKallankari** [pnuu/fmiopendata#39]
I'm trying to run example code under paragrhap _Download and calibrate latest radar reflectivity (dBZ) composite_. 

Command _composite.download()_ fails with following error message:

```
Traceback (most recent call last):
  File "rasterio\_base.pyx", line 310, in rasterio._base.DatasetBase.__init__
  File "rasterio\_base.pyx", line 221, in rasterio._base.open_dataset
  File "rasterio\_err.pyx", line 221, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: C:/Users/xxxx/AppData/Local/Temp/tmp42opk8v9: file used by other process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    composite.download()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\fmiopendata\radar.py", line 77, in download
    img = rasterio.open(fid.name)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\rasterio\env.py", line 451, in wrapper
    return f(*args, **kwds)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\rasterio\__init__.py", line 320, in open
    dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
  File "rasterio\_base.pyx", line 312, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: C:/Users/xxxx/AppData/Local/Temp/tmp42opk8v9: file used by other process
```
Any ideas why example code is not working. I'm running Windows 10 and pyhthon 3.11.

**Comment by pnuu** [comment]
Sorry for the very late answer. This could be something with how Windows handles files. I've seen something similar in other Python libraries where they have to do workarounds for Windows file handling. I should perhaps add automated Windows tests, but might not be able to solve the problems without an actual access to a Windows machine.

**Comment by jaakkolehtinen** [comment]
Bump, I have the same issue.
